
ekf_se_odom:
  frequency: 25
  # sensor_timeout: 0.5
  two_d_mode: true
  transform_time_offset: 0.0
  transform_timeout: 0.0
  print_diagnostics: true
  debug: false

  map_frame: map
  odom_frame: odom
  base_link_frame: base_link
  world_frame: odom

  odom0: hibachi_velocity_controller/odom
  odom0_config: [false, false, false,
                 false, false, false,
                 true,  true, true,
                 false, false, true,
                 false, false, false]
  odom0_queue_size: 10
  odom0_nodelay: true
  odom0_differential: true
  odom0_relative: false

  imu0: /mti_630_8A1G6/imu/data
  imu0_config: [false, false, false,   # x,   y,   z
                true,  true,  true,    # r,   p,   w (yaw)
                false, false, false,   # dx,  dy,  dz
                false,  false,  true,    # dr,  dp,  dw
                false,  false,  false] # ddx, ddy, ddz
  imu0_nodelay: true
  imu0_differential: false
  imu0_relative: true
  imu0_queue_size: 10
  imu0_remove_gravitational_acceleration: true
  use_control: false


ekf_se_map:
  frequency: 25
  # sensor_timeout: 0.5
  two_d_mode: true
  transform_time_offset: 0.0
  transform_timeout: 0.0
  print_diagnostics: true
  debug: false
  # dynamic_process_noise_covariance: false

  map_frame: map
  odom_frame: odom
  base_link_frame: base_link
  world_frame: map

  odom0: hibachi_velocity_controller/odom
  odom0_config: [false, false, false,    # x,   y,   z
                 false, false, false,    # r,   p,   w (yaw)
                 true,  true,  true,     # dx,  dy,  dz
                 false, false, true,     # dr,  dp,  dw
                 false, false, false]    # ddx, ddy, ddz

  odom0_queue_size: 5
  odom0_nodelay: true
  odom0_differential: true
  odom0_relative: false

  odom1: odometry/gps
  odom1_config: [true,  true,  false, # x,   y,   z
                 false, false, false, # r,   p,   w (yaw)
                 false, false, false, # dx,  dy,  dz
                 false, false, false, # dr,  dp,  dw
                 false, false, false] # ddx, ddy, ddz

  odom1_queue_size: 10
  odom1_nodelay: true
  odom1_differential: false
  odom1_relative: false

  imu0: /mti_630_8A1G6/imu/data
  imu0_config: [false, false, false,   # x,   y,   z
                true, true,  true,    # r,   p,   w (yaw)
                false, false, false,   # dx,  dy,  dz
                true,  true,  true,    # dr,  dp,  dw
                false,  false,  false] # ddx, ddy, ddz
  imu0_nodelay: true
  imu0_differential: false
  imu0_relative: true
  imu0_queue_size: 10
  imu0_remove_gravitational_acceleration: true
  use_control: false

navsat_transform:
  frequency: 25
  delay: 0.0
  magnetic_declination_radians: 0.1623 # For lat/long
  yaw_offset: 0.0  # 1.5707963 if IMU reads 0 facing magnetic north, not east
  zero_altitude: true
  # broadcast_utm_transform: true
  broadcast_cartesian_transform: true
  broadcast_cartesian_transform_as_parent_frame: false
  publish_filtered_gps: true
  use_odometry_yaw: false
  wait_for_datum: false
  # datum: [-31.5384378771, -60.496496369, 0.0] # Coords masked for online publishing
