obstacle_range: 2.5 #5.5
raytrace_range: 3.0 #6.0

footprint: [[-0.25, -0.2], [-0.25, 0.2], [0.25, 0.2], [0.25, -0.2]]
#footprint_padding: 0.01
inflation_radius: 0.55 #0.2

observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: rplidar_a1, data_type: LaserScan, topic: scan, clearing: true, marking: true, inf_is_valid: true}

#robot_base_frame: base_link

#update_frequency: 5.0
#publish_frequency: 5.0

#transform_tolerance: 0.5
#resolution: 0.01