<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find hibachi_description)/urdf/inertial_macros.xacro" />
    <xacro:include filename="$(find hibachi_description)/urdf/wheel.urdf.xacro" />
    
	<!--  Wheel distance between front and rear -->
	<xacro:property name="wheel_distance" value="0.2" />

	<!-- Wheel distance between left and right side -->
	<xacro:property name="wheel_separation" value="0.34" />

	<!-- Wheel properties -->
	<xacro:property name="wheel_mass" value="0.150" />
	<xacro:property name="wheel_radius" value="0.06" />
	<xacro:property name="wheel_width" value="0.06" />

	<!-- Chassis size -->
	<xacro:property name="chassis_x_size" value="0.40" />
	<xacro:property name="chassis_y_size" value="0.25" />
	<xacro:property name="chassis_z_size" value="0.05" />

	<!-- https://docs.ros.org/en/humble/Tutorials/Intermediate/URDF/Adding-Physical-and-Collision-Properties-to-a-URDF-Model.html -->

    <link name="base_link">

		<visual>
    		<origin xyz="0 0 0.0278" rpy="${(pi/2)} 0 ${-(pi/2)}"/>
			<geometry>
				<mesh filename="file://$(find hibachi_description)/meshes/hibachi_chassis.stl" scale="0.001 0.001 0.001" />
			</geometry>
			<material name="Red">
				<color rgba="${255/255} ${0/255} ${0/255} 1.0"/>
			</material>
		</visual>

		<collision>
			<origin xyz="0 0 0"/>
			<geometry>
				<box size="${chassis_x_size} ${chassis_y_size} ${chassis_z_size}"/>
			</geometry>
		</collision>
    </link>

	<!-- Base footprint is on the ground under the robot -->
    <link name="base_footprint">
		<xacro:dummy_inertial />
	</link>

    <joint name="base_footprint_joint" type="fixed">
        <origin xyz="0 0 ${-wheel_radius}" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="base_footprint" />
    </joint>

	<!-- Interial link stores the robot's inertial information -->
    <link name="inertial_link">
		<xacro:inertial_box mass="2.0" x="${chassis_x_size}" y="${chassis_y_size}" z="${chassis_z_size}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <joint name="inertial_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="inertial_link" />
    </joint>

	<!-- Wheel macros -->
	<xacro:hibachi_wheel wheel_prefix="front_left">
		<origin xyz="${wheel_distance/2} ${wheel_separation/2} 0" rpy="0 0 0" />
	</xacro:hibachi_wheel>

	<xacro:hibachi_wheel wheel_prefix="front_right">
		<origin xyz="${wheel_distance/2} ${-wheel_separation/2} 0" rpy="0 0 0" />
	</xacro:hibachi_wheel>

	<xacro:hibachi_wheel wheel_prefix="rear_left">
		<origin xyz="${-wheel_distance/2} ${wheel_separation/2} 0" rpy="0 0 0" />
	</xacro:hibachi_wheel>

	<xacro:hibachi_wheel wheel_prefix="rear_right">
		<origin xyz="${-wheel_distance/2} ${-wheel_separation/2} 0" rpy="0 0 0" />
	</xacro:hibachi_wheel>

    <!-- Sensors -->

	<!-- MTI630 IMU -->
	<link name="xsens_imu_link">
		<xacro:dummy_inertial />
	</link>

	<joint name="xsens_imu_joint" type="fixed">
		<parent link="base_link" />
		<child link="xsens_imu_link" />
		<origin xyz="0 0 0.05" rpy="0 0 0" />
	</joint>

	<!-- RPLidar A1 -->
	<link name="rplidar_a1_link">
		<xacro:dummy_inertial />
		<collision>
			<origin xyz="0 0 0.0275" rpy="0 0 0"/>
			<geometry>
				<box size="0.0968 0.0703 0.0550"/>
			</geometry>
		</collision>
		<visual>
			<geometry>
				<mesh filename="file://$(find hibachi_description)/meshes/rplidar_a1.dae"  />
			</geometry>
		</visual>
	</link>

	<joint name="rplidar_joint" type="fixed">
		<parent link="base_link"/>
		<child link="rplidar_a1_link"/>
		<origin xyz="0 0 0.12" rpy="0 0 0"/>
	</joint>

	<link name="ardusimple_gps_link">
		<xacro:dummy_inertial />
	</link>

	<joint name="ardusimple_gps_joint" type="fixed">
		<parent link="base_link" />
		<child link="ardusimple_gps_link" />
		<origin xyz="0.0 -0.1 0.2" rpy="0 0 0" />
	</joint>

	<link name="m8n_gps_link">
		<xacro:dummy_inertial />
	</link>

	<joint name="m8n_gps_joint" type="fixed">
		<parent link="base_link" />
		<child link="m8n_gps_link" />
		<origin xyz="0.0 0.1 0.2" rpy="0 0 0" />
	</joint>

	

</robot>