hibachi_state_publisher:
  type: "joint_state_controller/JointStateController"
  publish_rate: 10

hibachi_velocity_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: ['front_left_wheel', 'rear_left_wheel']
  right_wheel: ['front_right_wheel', 'rear_right_wheel']
  publish_rate: 10

  pose_covariance_diagonal: [0.001, 0.001, 100.0, 100.0, 100.0, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 100.0, 100.0, 0.03]

  cmd_vel_timeout: 0.25
  publish_cmd: True

  wheel_separation: 0.34
  wheel_radius: 0.06  # 12 cm de diametro
  k_l: 0.1
  k_r: 0.1

  enable_odom_tf: True

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.15 # default: 1.0

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 0.5   # m/s
      has_acceleration_limits: true
      max_acceleration       : 5.0   # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 2.0   # rad/s
      has_acceleration_limits: true
      max_acceleration       : 10.0  # rad/s^2